apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: orm
  name: orm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orm
  template:
    metadata:
      labels:
        io.kompose.service: orm
    spec:
      containers:
      - image: multiple-containers-in-pod_orm:latest
        imagePullPolicy: "IfNotPresent"
        name: orm
        ports:
        - containerPort: 5431
          hostPort: 5431
        resources: {}
      - image: multiple-containers-in-pod_db:latest
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        imagePullPolicy: "IfNotPresent"
        name: db
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always

